'use client'
import { useState } from 'react'

type Invoice={id:string,vendor:string,po:string,total:string,status:'Approved'|'Review',match:string}
const seed:Invoice[]=[{id:'INV-1048',vendor:'Acme Supplies',po:'PO-1042',total:'₹48,500',status:'Approved',match:'Exact match'},{id:'INV-1049',vendor:'Nova Office Co.',po:'PO-1043',total:'₹52,000',status:'Review',match:'Amount mismatch: ₹3,500'},{id:'INV-1050',vendor:'Vertex Systems',po:'PO-1044',total:'₹31,200',status:'Approved',match:'Exact match'},{id:'INV-1051',vendor:'CloudNine Ltd.',po:'PO-1045',total:'₹18,750',status:'Approved',match:'Exact match'}]

export default function Home(){
 const [invoices,setInvoices]=useState(seed); const [file,setFile]=useState(''); const [notice,setNotice]=useState('')
 function process(){ if(!file){setNotice('Select an invoice first.');return} const n:Invoice={id:'INV-'+(1052+invoices.length),vendor:file.replace(/\.[^.]+$/,'').slice(0,24)||'Uploaded Vendor',po:'PO-NEW',total:'₹42,800',status:'Approved',match:'AI extraction + PO match passed'};setInvoices([n,...invoices]);setNotice('AI processed invoice: extraction complete and PO validation passed.')} 
 function approve(id:string){setInvoices(x=>x.map(i=>i.id===id?{...i,status:'Approved'}:i));setNotice('Approval sent to Slack workflow (demo).')}
 return <main className="shell"><header className="top"><div><div className="brand">Invoice AI Agent</div><div className="sub">AI extraction · PO validation · approval workflow</div></div><span className="pill">● System operational</span></header>
 <section className="grid"><Metric label="Total invoices" value={String(invoices.length+16)} /><Metric label="Processed" value={String(invoices.length+16)} /><Metric label="Approved" value={String(invoices.filter(x=>x.status==='Approved').length+14)} /><Metric label="Flagged" value={String(invoices.filter(x=>x.status==='Review').length+2)} /></section>
 <section className="main"><div className="card"><div className="section-title">Process invoice</div><div className="upload"><div style={{fontSize:28}}>↥</div><div style={{fontWeight:700,margin:'8px 0'}}>Drop an invoice or choose a file</div><div className="sub">PDF, PNG or JPG · AI extracts invoice fields automatically</div><input style={{marginTop:18}} type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]?.name||'')} /><div style={{marginTop:16}}>{file&&<span className="muted">Selected: {file}</span>}</div><button className="btn primary" style={{marginTop:14}} onClick={process}>Process with AI</button></div>{notice&&<div style={{marginTop:14,padding:12,borderRadius:9,background:'#f1f5f9',fontSize:13}}>{notice}</div>}</div>
 <div className="card"><div className="section-title">AI accuracy</div><div className="accuracy">90%</div><div className="muted">18 / 20 test invoices correct</div><div style={{marginTop:22}}><Accuracy name="Invoice number" n="100%" w="100%"/><Accuracy name="Vendor" n="95%" w="95%"/><Accuracy name="PO number" n="100%" w="100%"/><Accuracy name="Date" n="95%" w="95%"/><Accuracy name="Total" n="90%" w="90%"/></div></div></section>
 <section className="card" style={{marginTop:16}}><div className="section-title">Recent invoices</div><div className="table-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Vendor</th><th>PO</th><th>Total</th><th>Validation</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><b>{i.id}</b></td><td>{i.vendor}</td><td>{i.po}</td><td>{i.total}</td><td><span className={'status '+(i.status==='Approved'?'ok':'warn')}>{i.status==='Approved'?'✓ ': '⚠ '}{i.match}</span></td><td><span className={'status '+(i.status==='Approved'?'ok':'warn')}>{i.status}</span></td><td>{i.status==='Review'?<div className="row-actions"><button className="btn green" onClick={()=>approve(i.id)}>Approve</button><button className="btn red" onClick={()=>setNotice('Invoice rejected and sent back for review.')}>Reject</button></div>:<span className="muted">Slack ✓</span>}</td></tr>)}</tbody></table></div></section>
 <section className="card" style={{marginTop:16}}><div className="section-title">How the agent works</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{['1. Extract','2. Match PO','3. Decide','4. Notify'].map((x,i)=><div key={x} style={{padding:14,border:'1px solid var(--line)',borderRadius:10}}><b>{x}</b><div className="sub">{['LLM reads invoice fields','Checks vendor, PO and totals','Auto-approves or flags exceptions','Sends approval to Slack'][i]}</div></div>)}</div></section>
 </main>
}
function Metric({label,value}:{label:string,value:string}){return <div className="card"><div className="label">{label}</div><div className="metric">{value}</div></div>}
function Accuracy({name,n,w}:{name:string,n:string,w:string}){return <div style={{marginBottom:13}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,fontWeight:700}}><span>{name}</span><span>{n}</span></div><div className="bar"><div className="fill" style={{width:w}}/></div></div>}
